# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Simulation(QtWidgets.QDialog):
    def __init__(self, router_list, destination_addr_list):
        super(Ui_Simulation, self).__init__()
        self.router_list = router_list
        self.destination_addr_list = destination_addr_list
        self.destination_addr_count = 0
        self.router_list_count = 0
        self.setupUi(self)

    def setupUi(self, Dialog):
        self.dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(1012, 836)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("font: 18pt \"仿宋\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.destination_net_label = QtWidgets.QLabel(self.frame)
        self.destination_net_label.setStyleSheet("font: 18pt \"仿宋\";")
        self.destination_net_label.setText("")
        self.destination_net_label.setObjectName("destination_net_label")
        self.horizontalLayout.addWidget(self.destination_net_label)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(180)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setDefaultSectionSize(126)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font: 18pt \"仿宋\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(600, 20, -1, 20)
        self.horizontalLayout_2.setSpacing(70)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setStyleSheet("font: 14pt \"华文琥珀\";\n"
"background-color: rgb(0, 255, 127);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setStyleSheet("font: 14pt \"华文琥珀\";\n"
"background-color: rgb(0, 255, 127);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(Dialog.close)
        self.pushButton.clicked.connect(self.update_status)

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def update_status(self):
        _translate = QtCore.QCoreApplication.translate
        if self.destination_addr_count == len(self.destination_addr_list):
            QMessageBox.information(self.dialog, '提示', '已到末尾，将自动重置。')
            self.destination_addr_count = 0

        for i, text in enumerate(self.destination_addr_list[self.destination_addr_count].decimal_int_list):
            self.tableWidget.setItem(1, i, QtWidgets.QTableWidgetItem(text))

        des = self.router_list.destination_network_list[self.router_list_count]
        sub = self.router_list.subnet_mask_list[self.router_list_count]

        des_text = '第{}行，{}'.format(self.router_list_count + 1, des.ipv4_addr) if des != 'None' else 'None'
        self.destination_net_label.setText(des_text)
        if sub != 'None':
            for i, text in enumerate(sub.decimal_int_list):
                self.tableWidget.setItem(0, i, QtWidgets.QTableWidgetItem(text))
            new_ipv4 = sub.cal_and(self.destination_addr_list[self.destination_addr_count])
            for i, text in enumerate(new_ipv4.decimal_int_list):
                self.tableWidget.setItem(2, i, QtWidgets.QTableWidgetItem(text))

            if new_ipv4.if_the_same_ip(des):
                self.destination_addr_count += 1
                self.label_2.setText(_translate("Dialog", "当前结果：匹配，下一跳为{}".format(self.router_list.next_list[self.router_list_count])))
                self.router_list_count = 0
            else:
                self.label_2.setText(_translate("Dialog", "当前结果：未匹配"))
                self.router_list_count += 1
        else:
            for i in range(0, 4):
                self.tableWidget.setItem(0, i, QtWidgets.QTableWidgetItem('None'))
                self.tableWidget.setItem(2, i, QtWidgets.QTableWidgetItem('None'))
            self.destination_addr_count += 1
            self.label_2.setText(
                _translate("Dialog", "当前结果：无匹配，下一跳为默认{}".format(self.router_list.next_list[self.router_list_count])))
            self.router_list_count = 0




    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "当前行路由表中的目的网络："))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "该网络的子网掩码"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "收到的分组的目的地址"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "与运算结果"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        self.label_2.setText(_translate("Dialog", "当前结果："))
        self.pushButton.setText(_translate("Dialog", "继续"))
        self.pushButton_2.setText(_translate("Dialog", "退出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
